### ISSUE TITLE
stylelint is not reporting any issue

### ISSUE THREAD

**Issue by mrfyda** [codacy/codacy-stylelint#65]
stylelint is not reporting any issue (for any file) when configured using the Codacy UI regardless of the rules configured.

The following example code should atleast find one occurrence of the rule `Unexpected empty block (block-no-empty)`:

```css
// неправильный комментарий

.hEad {

}



/*нет пробелов в комментарии, это ошибка*/

.wrap {

  position: ;

  display: block;

}

.main {color: aliceblue}

.link {
    color: aliceblue;

    background: antiquewhite;
  color: aqua;





      position:relative;
}
```
